from enum import Enum

SCHEMA_VERSION=2
DATASET_VERSION="1.1"
CAPTURE_VERSION="1.3"
class EventType(str,Enum):
    USER_REQUEST="USER_REQUEST"; STT_TRANSCRIPT="STT_TRANSCRIPT"; NORMALIZED_REQUEST="NORMALIZED_REQUEST"; RESOLVED_REFERENCES="RESOLVED_REFERENCES"; PLAN_CREATED="PLAN_CREATED"; REASONING_REQUEST="REASONING_REQUEST"; REASONING_RESPONSE="REASONING_RESPONSE"; TOOL_CALL="TOOL_CALL"; TOOL_RESULT="TOOL_RESULT"; CODE_PATCH="CODE_PATCH"; TEST_RUN="TEST_RUN"; TEST_RESULT="TEST_RESULT"; USER_CORRECTION="USER_CORRECTION"; USER_APPROVAL="USER_APPROVAL"; USER_REJECTION="USER_REJECTION"; TASK_STARTED="TASK_STARTED"; TASK_PAUSED="TASK_PAUSED"; TASK_RESUMED="TASK_RESUMED"; TASK_CANCELLED="TASK_CANCELLED"; TASK_COMPLETED="TASK_COMPLETED"; TASK_FAILED="TASK_FAILED"; TASK_BLOCKED="TASK_BLOCKED"; FINAL_RESPONSE="FINAL_RESPONSE"
class QualityLabel(str,Enum):
    UNVERIFIED="UNVERIFIED"; SUCCESS="SUCCESS"; VERIFIED_SUCCESS="VERIFIED_SUCCESS"; FAILED="FAILED"; CORRECTED="CORRECTED"; USER_APPROVED="USER_APPROVED"; USER_REJECTED="USER_REJECTED"; REGRESSION="REGRESSION"; ROLLED_BACK="ROLLED_BACK"; AMBIGUOUS="AMBIGUOUS"; BLOCKED="BLOCKED"
VALID_EVENTS={item.value for item in EventType}; VALID_LABELS={item.value for item in QualityLabel}
